# -*- coding: utf-8 -*-
"""School Catalogue (Codecademy)

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1n1KNe4Fh8EssK3WG673nU6yet08XSd5y
"""

class School:
  def __init__(self, name, level, numberOfStudents):
    self.name = name
    self.level = level
    self.numberOfStudents = numberOfStudents

  def get_name (self):
    return self.name

  def get_level(self):
      return self.level

  def get_numberOfStudents(self):
    return self.numberOfStudents

  def set_numberOfStudents(self, newnumberOfStudents):
    self.numberOfStudents = newnumberOfStudents

  def __repr__(self):
    return ('A {} school named {} with {} students'.format(self.level, self.name, self.numberOfStudents))

#testing code above
a = School("Codecademy", "high", 100)
print(a)
print(a.get_name())
print(a.get_level())
a.set_numberOfStudents(200)
print(a.get_numberOfStudents())
# Repeating code for Primary school using inheritance
class PrimarySchool(School):
  #inserting constructor to stop repeating tasks already done above
  def __init__(self, name, numberOfStudents, pickupPolicy):
    super().__init__(name, "primary", numberOfStudents)
    self.pickupPolicy = pickupPolicy

  def get_pickupPolicy(self):
    return self.pickupPolicy

  def __repr__(self):
    school = super().__repr__()
    return school + " The pickup policy is {pickupPolicy}".format(pickupPolicy=self.pickupPolicy)
# creating the PrimaryScool pickupolicy object to test code
b = PrimarySchool("Codecademy", 300, "Pickup Allowed")
print(b.get_pickupPolicy())
print(b)

# Creating Highschool class with minimal help

class HighSchool(School):
  def __init__(self, name, numberOfStudents, sportsTeams):
    super().__init__(name, "high", numberOfStudents)
    self.sportsTeams = sportsTeams

  def get_sportsTeams(self):
    return self.sportsTeams

  def __repr__(self):
    school = super().__repr__()
    return school + " The sportsteams we have are {sportsTeams}".format(sportsTeams=self.sportsTeams)


c = HighSchool("Codecademy", 400, ["Tennis", "Basketball"])
print(c.get_sportsTeams())
print(c)